### ISSUE TITLE
No output is produced

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [marianne-m/brouhaha-vad#10]
As far as I can tell, no output is produced by the current script. Only the directories.

```
 % find out
out
out/.DS_Store
out/c50
out/rttm_files
out/detailed_snr_labels
```

I saw no installation errors so everything looked ok.

**Comment by marianne-m** [comment]
Hi !
Did you specify the right audiofile extension with the `--ext` option ?
If your audiofiles are in subdirectories, you need to use the `--recursive` option.

I hope this helps !

**Comment by MarvinLvn** [comment]
Maybe, we can throw an error when no audio file has been found? (and suggest the user to use the `--ext` parameter or the `--recursive` flag)
