### ISSUE TITLE
Can convert  to onnx model？

### ISSUE THREAD

**Issue by zuowanbushiwo** [marianne-m/brouhaha-vad#11]
Hi @marianne-m 
      Can this model be converted to onnx? I want to use C++ inference on the mobile side? thanks!

**Comment by MarvinLvn** [comment]
Hi,

We've never really tried converting pytorch model to onnx. So I'm afraid we won't be of much help.
However, some pyannote users asked the same in this [issue](https://github.com/pyannote/pyannote-audio/issues/702) (with a code snippet)

I hope this helps!

**Comment by zuowanbushiwo** [comment]
Thanks!

**Comment by dukeeagle** [comment]
Hey @zuowanbushiwo ! Did you end up getting this working?
