### ISSUE TITLE
no attributes 'introspection'

### ISSUE THREAD

**Issue by ljr10225008** [marianne-m/brouhaha-vad#13]
Dear Marvin,

When running the codes, the following errors occurred,
![image](https://github.com/marianne-m/brouhaha-vad/assets/61999816/4df28203-bd0d-4534-81c5-ee6f60efc624)
I tried on both Windows and Ubuntu, and the same error occurred. There is no problem when doing the installation.

Could you let me know how to solve the problem?

regards,
Jiarui

**Comment by arthuruan** [comment]
Same error on Mac. 

![image](https://github.com/marianne-m/brouhaha-vad/assets/49700636/b95441f7-fbe3-4388-b23c-26b482246c51)

**Comment by DeivisonJordao** [comment]
![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/86767c94-354d-4664-a26c-cdd0ca9d7b49)

**Comment by marianne-m** [comment]
Hi !
Which `pyannote.audio` version do you have ? I reproduced the error if the version >= 3.0.0.
You can downgrade it with `pip install pyannote.audio==2.1.1`.
I'll update the requirements file :)

**Comment by shenberg** [comment]
Note: on mac pyannote.audio==2.1.1 fails to install due to the hmmlearn dependency failing to build, I commented-out the line and used pyannote.audio==3.0.0 🙈

**Comment by ljr10225008** [comment]
Pyannote.audio==2.1.1 worked on Ubuntu! Thanks!

**Comment by marianne-m** [comment]
Brouhaha now works with pyannote.audio==3.0, so you can use it on mac !

**Comment by arthuruan** [comment]
it worked, thanks!
