### ISSUE TITLE
pip install https://github.com/marianne-m/pyannote-brouhaha-db.git   DONT WORK

### ISSUE THREAD

**Issue by DeivisonJordao** [marianne-m/brouhaha-vad#16]
![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/cdc5d83f-c285-4721-af65-fcd2c8e56d8a)

pip install https://github.com/marianne-m/pyannote-brouhaha-db.git  

DONT WORK

Could you help me find out why? because I followed all the steps correctly. I want to finetune the model.

![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/064d1e43-8547-48f3-ad99-02998d401287)

I also tried this way:

pip install git+ssh://git@github.com:marianne-m/pyannote-brouhaha-db.git

![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/845cbc8b-b321-447b-bcd9-5bf672983141)

and dont work too

**Comment by MarvinLvn** [comment]
If you haven't configured your git account to allow ssh, these commands will not work.

In your case, you can install the repo using: 

```
pip install git+https://github.com/marianne-m/pyannote-brouhaha-db.git
```

**Comment by DeivisonJordao** [comment]
thanks!!! it worked out.
