### ISSUE TITLE
Where is the ~/.pyannote/database.yml ??

### ISSUE THREAD

**Issue by DeivisonJordao** [marianne-m/brouhaha-vad#17]
![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/97d0a3dd-f17b-4b28-a8a1-d5077a9ae9a7)

where is this file?? I can not find, Can you help me with this? detail the path

One of the places I looked was this:
/home/deivison/workspace/VAD/miniconda3/envs/brouhaha/lib/python3.8/site-packages/pyannote

I also tried creating the .yml in the database directory:
![image](https://github.com/marianne-m/brouhaha-vad/assets/81170028/b27942d1-3526-4fa2-9ab3-69af528ec824)

Could you detail the process to do this fine-tuning step in more detail?

**Comment by DeivisonJordao** [comment]
@hbredin @hadware @MarvinLvn @marianne-m  
 
Can you help me??

**Comment by hadware** [comment]
The "~" at the beginning of the path name indicates that it has to be in your home folder, `/home/deivision/` in your case.
If you meant "what is the file i'm supposed to use as a reference", well, the example given in the document _is_ the example content of the file.

Also, please don't tag people like this, else, the ghost of @hbredin is going to come and haunt you in your sleep.

**Comment by arthuruan** [comment]
Thanks for your explanation! I actually have the same problem. I'm not 100% sure, but I think it's related to the `pyannote-database` version, looks like the `pyannote-bouhaha` is instaled with the version 5.x of  `pyannote-database` and second its [documentation](https://github.com/pyannote/pyannote-database?tab=readme-ov-file#configuration-file) the `~/.pyannote/database.yml` is loaded automatically just in backward versions of 4.x . Do you have some thoutghs about what I can do to work using the version 5.x? I already tried to create it manually, but no success. I appreaciate your attention!

**Comment by MarvinLvn** [comment]
@deivisongithub 

```
where is this file?? I can not find, Can you help me with this? detail the path
```

The path is ~/.pyannote/database.yml as indicated [here](https://github.com/marianne-m/brouhaha-vad/blob/main/doc/training.md). You must create the file yourself. It could be helpful to read the [pyannote-database](https://github.com/pyannote/pyannote-database) doc.

```
@hbredin @hadware @MarvinLvn @marianne-m
Can you help me??
```

Spamming won't make it any faster.

@arthuruan 

```
I actually have the same problem. I'm not 100% sure, but I think it's related to the pyannote-database version, looks like the pyannote-bouhaha is installed with the version 5.x of pyannote-database and second its [documentation](https://github.com/pyannote/pyannote-database?tab=readme-ov-file#configuration-file) the ~/.pyannote/database.yml is loaded automatically just in backward versions of 4.x .
```

If you're referring to the `Could not find any protocol for "Brouhaha" database` error, it just indicates that you did not declare a  Brouhaha database in `database.yml`. I'm not sure what makes you think it's related to the `pyannote-database` version, but maybe it is. Have you tried downgrading?

**Comment by DeivisonJordao** [comment]
Sorry about the tags, I didn't know they were inconvenient. And thank you very much for your attention.

But, I also tried to find the .pyannote/ in my /home/deivison/, but apparently it doesn't exist. I know it's a hidden file, but I'm checking with "ls -a". Do you have any idea what's going on?

**Comment by MarvinLvn** [comment]
You must create both the folder `/home/deivison/.pyannote` and the file `database.yml` ...

I'm closing the issue as it has become apparent it's not related to a bug.
