### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by hbredin** [marianne-m/brouhaha-vad#2]
We need  to decide on license for the code and for the model.

I'd go for 
* MIT for the code ([same as pyannote](https://github.com/pyannote/pyannote-audio/blob/develop/LICENSE) to make future integration easier)
* [OpenRAIL](https://huggingface.co/blog/open_rail) for the model

Any thoughts @marianne-m @MarvinLvn ?

**Comment by MarvinLvn** [comment]
Added MIT LICENSE file for the code.
I think the choice of OpenRAIL for the model is great!

Thanks!
Closing :)
