### ISSUE TITLE
[BUG] in einops but impact to brouhaha model forward()

### ISSUE THREAD

**Issue by yoesak** [marianne-m/brouhaha-vad#20]
I found in the brouhaha-vad using the einops and cause this error "AttributeError: 'PyanNet' object has no attribute 'example_output'", the solution is changing with the torch.permute() function, 

`def forward(self, x: torch.Tensor):
        .. 
        out = rearrange(out, "n b t o -> b t (n o)")
        return out`
`

how do I retrain the model (best.ckpt) with the new implementation? 

this is the same is issue like in here 

https://github.com/pyannote/pyannote-audio/issues/1620

**Comment by MarvinLvn** [comment]
Should be solved by https://github.com/marianne-m/brouhaha-vad/pull/21
Shout out to @ylacombe !
