### ISSUE TITLE
Wrong model specifications

### ISSUE THREAD

**Issue by hbredin** [marianne-m/brouhaha-vad#5]
```python
model = Model.from_pretrained("models/best/checkpoints/best.ckpt")
model.specification
# Specifications(problem=<Problem.MULTI_LABEL_CLASSIFICATION: 2>, 
#                resolution=<Resolution.FRAME: 1>, 
#                duration=6, 
#                warm_up=(0.0, 0.0), 
#                classes=['speech'], 
#                permutation_invariant=False)
```

Would be nice to update `classes` to ['vad', 'snr', 'c50'].

**Comment by MarvinLvn** [comment]
I fixed it with commit https://github.com/marianne-m/brouhaha-vad/commit/192c0dd760e8018e611f6b89e70bb1b8fff51098
I changed it in the pretrained model and in the code to avoid mismatch with future trainings.

Thanks for raising this issue! 

Closing :)
