### ISSUE TITLE
Syntax in the documentation is not correct

### ISSUE THREAD

**Issue by orasanen** [marianne-m/brouhaha-vad#9]
Syntax for applying the model to data, as given in the readme.md, is not correct. 

This works
```
python main.py apply --apply_folder my/path/to_folder/ --model_path models/best/checkpoints/best.ckpt --data_dir my/path/to_folder/ --ext wav
```

but the command given in the readme doesn't, as it is missing --apply_folder argument and has extra argument (--classes) not accepted by the main.py for apply.

**Comment by hadware** [comment]
This is correct, sorry for this.

@marianne-m I updated the `main.py`'s arguments for apply, and fixed the README, could you confirm that this is right?

**Comment by marianne-m** [comment]
While looking at this, I reorganized the arguments for the apply.
Here is the new correct command:
```
python main.py apply \
      --data_dir path/to/data \
      --out_dir path/to/predictions \
      --model_path models/best/checkpoints/best.ckpt \
      --ext "wav"
```
I updated the README too

**Comment by orasanen** [comment]
Perfect, thank you!
